import { Badge } from "lucide-react";

export type ListingProperty = {
  id: number;
  title: string;
  location: string;
  price: string;
  image: string;
  beds: number;
  rest: number;
  sqft: string;
  type: string;
  yearBuilt: number;
  lotSize: string;
  description: string;
  carousel?: string[];
};

export const listingsProperties = [
  {
    id: 1,
    title: "The Mulia Bali",
    location: "Nusa Dua, Bali",
    price: "940,999,999",
    image: "/mulia.webp",
    beds: 526,
    rest: 9,
    sqft: "299.460",
    type: "Resort",
    yearBuilt: 2012,
    lotSize: "N/A",
    description:
      "The Mulia, Mulia Resort & Villas – Nusa Dua, Bali is a luxury beachfront resort offering elegant suites, private villas with pools, a world-class spa, an iconic infinity pool, and 9 exclusive restaurants and bars. Located in the premium area of Nusa Dua, this property stands out as a top destination for holidays, special events, and high-class international hospitality investments.",
    features: [
      "Airport Shuttle / Transfers",
      "Meeting & Conference Rooms",
      "Multiple Outdoor Swimming Pools (≈ 6)",
      "Exclusive Infinity Pool (Oasis Pool) for The Mulia & Villas guests",
      "Private Beach / Beachfront Access (Geger Beach)",
      "Full Spa & Wellness Centre (ice room, sauna, steam room, hot & cold hydrotherapy)",
      "Kids Club / T-Zone for different age groups",
      "9 Restaurants & Bars with international & local cuisine",
      "Gym / Fitness Centre",
      "Tennis Courts",
      "Poolside Bars & Loungers / Cabanas",
      "Garden & Terrace Area",
      "Nightlife & Lounge Venues (Sky Bar, evening bars)",
      "24-hour Room Service",
      "Free WiFi in rooms & public areas",
      "Private Balcony / Terrace in rooms",
      "Luxury Bathrooms (separate bathtub & shower, jetted bathtub, outdoor shower – depending on room type)",
      "Premium bedding & in-room amenities",
    ],
    amenities: [
      "Air Conditioning",
      "Flat-Screen TV",
      "Free Wi-Fi",
      "Minibar",
      "Coffee & Tea Maker",
      "Balcony / Terrace with ocean or garden view",
      "Living Area (selected rooms & suites)",
      "Marble Bathroom",
      "Separate Bathtub & Shower",
      "Hair Dryer",
      "In-Room Safe",
      "Work Desk",
      "Premium Toiletries",
      "24-hour Room Service",
    ],
    carousel: [
      "/mulia.webp",
      "/mulia3.webp",
      "/mulia2.webp",
      "/mulia4.webp",
    ],
  },
  {
    id: 2,
    title: "Keraton Jimbaran",
    location: "Jimbaran, Bali",
    price: "39,999,999",
    image: "/keraton3.jpg",
    beds: 102,
    rest: 2,
    sqft: "15.400",
    type: "Beach Resort",
    yearBuilt: 1991,
    lotSize: "N/A",
    description:
      "Keraton Jimbaran Resort is a traditional Balinese-style beachfront retreat located directly on the shores of Jimbaran Bay. Surrounded by lush tropical gardens, the resort features elegantly designed rooms and villas with classic Balinese architecture, an outdoor swimming pool, a relaxing spa, and direct access to Jimbaran’s white sandy beach. With its serene atmosphere and authentic cultural touches, Keraton Jimbaran is the perfect choice for a peaceful getaway or a truly immersive Balinese experience.",
    features: [
      "Airport Shuttle",
      "Meeting Rooms",
      "Outdoor Swimming Pool",
      "Private Beach Access",
      "Spa & Wellness Centre",
      "Restaurant",
      "Bar",
      "Free Wi-Fi",
      "Free Parking",
      "Private Pool Villas",
    ],
    amenities: [
      "Air Conditioning",
      "Flat-Screen TV",
      "Minibar",
      "Tea & Coffee Making Facilities",
      "Free Wi-Fi",
      "Balcony / Terrace",
      "Room Service",
      "Shower & Bathtub",
      "Hair Dryer",
      "Safety Box",
    ],
    carousel: [
      "/keraton.jpg",
      "/keraton2.jpg",
      "/keraton3.jpg",
      "/keraton4.jpg",
    ],
  },
  {
    id: 3,
    title: "Abi Bali Resort",
    location: "Jimbaran, Bali",
    price: "23,999,999",
    image: "/abi.png",
    beds: 32,
    rest: 1,
    sqft: "10.000",
    type: "Resort",
    yearBuilt: 2010,
    lotSize: "N/A",
    description:
      "Abi Bali Resort & Villas & Spa – Jimbaran, Bali is a modern tropical-style resort offering spacious rooms and private pool villas. With a restaurant, spa, fitness center, and complimentary shuttle service to the beach, the resort provides both comfort and privacy for romantic getaways or family holidays in the serene Jimbaran area.",
    features: [
      "Outdoor Swimming Pool",
      "Private Pool Villas",
      "Spa & Body Treatments (Massages, Facials, Body Scrubs)",
      "Fitness Center / Gym",
      "Restaurant (Spize Restaurant)",
      "Complimentary Beach Shuttle",
      "Airport Shuttle (surcharge)",
      "Meeting Rooms & Banquet Hall",
      "Free Wi-Fi throughout the property",
      "Free On-site Parking",
      "24-hour Room Service",
      "Dry Cleaning / Laundry Service",
      "Business Center",
      "Tropical Garden & Green Spaces",
      "Bathtub & Separate Shower",
      "Kitchenette in Villas (fully equipped)",
      "24-hour Reception",
      "Stereo Room / Lounge Area",
      "Tour & Ticket Assistance",
    ],
    amenities: [
      "Air Conditioning",
      "Flat-Screen TV",
      "Free Wi-Fi",
      "Minibar",
      "Coffee & Tea Maker",
      "Kitchenette (villa types only)",
      "Work Desk",
      "Living Area / Lounge",
      "Balcony / Terrace",
      "Bathtub & Separate Shower",
      "Hair Dryer",
      "Safety Box",
      "Telephone",
      "Complimentary Toiletries",
      "24-hour Room Service",

    ],
    carousel: [
      "/abi.png",
      "/abi2.png",
      "/abi3.png",
      "/abi4.jpg",
    ],
  },
  {
    id: 4,
    title: "Alam Ubud",
    location: "Ubud, Bali",
    price: "7,099,999",
    image: "/ubud.jpg",
    beds: 24,
    rest: 2,
    sqft: "40.000",
    type: "Hideaway Resort",
    yearBuilt: 2010,
    lotSize: "N/A",
    description:
      "Alam Ubud Culture Villas & Residences – Bali is a boutique resort set in the lush jungle of Ubud, surrounded by rivers and rice fields. It offers suites and private villas, some with private pools and valley views. Facilities include a spa, infinity pool, restaurant, and cultural activities like yoga and trekking. A peaceful escape just minutes from central Ubud, perfect for relaxation and nature lovers.",
    features: [
      "Outdoor Pool & Infinity Pool",
      "Private Pool Villas",
      "Restaurant & Bar / Lounge",
      "Spa & Wellness Centre (body treatments, massages, facials)",
      "Yoga Classes / Studio",
      "Room Service",
      "Airport Shuttle (surcharge)",
      "Free Wi-Fi in rooms & public areas",
      "Free Parking",
      "Laundry / Dry Cleaning Service",
      "Tropical Garden & Scenic Views (forest, valley, river)",
      "Balcony / Terrace in villas",
      "Air Conditioning & Non-Smoking Rooms",
      "Meeting / Banquet Facilities",
      "Outdoor Activities (trekking, cycling, horseback riding)",
    ],
    amenities: [
      "Air Conditioning & Free Wi-Fi",
      "Flat-Screen TV & Minibar",
      "Separate Bathtub & Shower",
      "Balcony / Terrace with Nature Views",
      "Private Pool (villa types)",
      "Restaurant & Bar",
      "Spa & Massage Services",
      "Room Service",
    ],
    carousel: [
      "/ubud.jpg",
      "/ubud2.jpg",
      "/ubud3.jpeg",
      "/ubud4.jpg",
    ],
  },
  {
    id: 5,
    title: "The Royal Beach",
    location: "Seminyak, Bali",
    price: "97,499,999",
    image: "/theroyal.webp",
    beds: 127,
    rest: 3,
    sqft: "43.000",
    type: "Beach Resort",
    yearBuilt: 1994,
    lotSize: "N/A",
    description:
      "The Royal Beach Seminyak Bali is a luxury beachfront resort set on 43,000 m² of lush tropical gardens in the heart of Seminyak. The property features elegant rooms and private pool villas, along with full facilities including a spa, restaurants, bars, and two outdoor swimming pools. With its prime location, it’s just steps away from Seminyak’s world-class dining, shopping, and entertainment.",
    features: [
      "Direct Access to Seminyak Beach (Beachfront)",
      "2 Outdoor Swimming Pools (oceanfront & garden)",
      "Private Villas with Pool or Jacuzzi",
      "Multiple Restaurants & Bars (Teppanyaki, International, Beachfront Bar)",
      "Spa & Wellness Centre",
      "Expansive Tropical Gardens",
      "Meeting Facilities / Ballroom",
      "Gym / Fitness Centre",
      "Kids Pool",
      "Free Wi-Fi Throughout the Property",
      "Free On-site Parking",
      "24-hour Front Desk",
      "24-hour Room Service",
      "Laundry / Dry Cleaning Services",
      "Prime Location near Seminyak's Dining & Entertainment"

    ],
    amenities: [
      "Free Wi-Fi Throughout the Property",
      "Air Conditioning (AC)",
      "In-room Minibar",
      "Smart TV / LED TV",
      "In-room Safe / Safety Deposit Box",
      "Hairdryer",
      "Bathrobe & Slippers",
      "Private Balcony / Terrace",
      "24-hour Room Service",
      "Free On-site Parking"

    ],
    carousel: [
      "/theroyal.webp",
      "/theroyal2.webp",
    ],
  },

]
